inherit_from:
  - .rubocop_airbnb.yml

Metrics/LineLength:
  Enabled: false

AllCops:
  Exclude:
    - bin/*
    - tmp/**/*
    - 'vendor/**/*'
    - Gemfile
    - Rakefile
    - channels/application_cable/*

Style/MixinUsage:
  Include:
    - app/**/*.rb

Rails/CreateTableWithTimestamps:
  Exclude:
    - 'db/migrate/20210624030047_create_active_storage_tables.active_storage.rb'
